import { browserStyles } from './browserStyles';

function attribute(value: string): string { return value.replace(/[&<>"']/g, (character) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' })[character]!); }
export function getLuaUtilitiesHtml(scriptUri: string, nonce: string): string {
    const safe = attribute(nonce);
    return `<!DOCTYPE html><html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta http-equiv="Content-Security-Policy" content="default-src 'none'; script-src 'nonce-${safe}'; style-src 'nonce-${safe}'; img-src 'none'; connect-src 'none'; font-src 'none'; base-uri 'none'; form-action 'none'">
<title>Lua Utilities</title><style nonce="${safe}">${browserStyles}
body{height:auto;min-height:100%}.app{height:auto;min-height:100vh}main{padding:22px 24px;max-width:1100px;width:100%;margin:auto}.tabs{display:flex;gap:8px;flex-wrap:wrap}.tabs button[aria-selected=true]{background:var(--vscode-button-background,#0078d4);color:var(--vscode-button-foreground,#fff)}.utility{display:flex;flex-direction:column;gap:12px}h2{font-size:18px;margin:0}.muted{color:var(--vscode-descriptionForeground,#aaa);margin:0;font-size:12px}.row{display:flex;gap:10px;align-items:end;flex-wrap:wrap}.field{display:flex;flex-direction:column;gap:5px;min-width:100px;flex:1}.field>label{font-size:12px}textarea{font:13px/1.5 var(--vscode-editor-font-family,monospace);color:var(--vscode-input-foreground,#eee);background:var(--vscode-input-background,#313131);border:1px solid var(--vscode-input-border,transparent);border-radius:3px;resize:vertical;padding:10px;width:100%;min-height:180px}textarea:focus-visible{outline:2px solid var(--vscode-focusBorder,#007fd4);outline-offset:2px}.output{display:grid;grid-template-columns:110px minmax(0,1fr) auto;align-items:center;gap:10px;border:1px solid var(--vscode-panel-border,#383838);padding:10px;border-radius:4px}.output code{overflow-wrap:anywhere}.output-label{font-size:12px;color:var(--vscode-descriptionForeground,#aaa)}.columns{display:grid;grid-template-columns:minmax(0,1fr) minmax(0,1fr);gap:16px}.color-control{width:90px;height:42px;padding:3px}.notice{margin:8px 0;overflow-wrap:anywhere}.target-bar{border-top:1px solid var(--vscode-panel-border,#383838);padding-top:16px;margin-top:24px}.target-bar p{margin:8px 0}.error{color:var(--vscode-errorForeground,#f48771)}#json-warnings{white-space:pre-wrap}.actions{display:flex;gap:8px;flex-wrap:wrap;margin:0}button{min-height:33px}#hash-input{font-family:var(--vscode-editor-font-family,monospace)}@media(max-width:650px){.columns{grid-template-columns:1fr}.output{grid-template-columns:85px minmax(0,1fr) auto}main{padding:18px 16px}header{padding:18px 16px}}
.notice{color:var(--vscode-foreground,#ddd);border-color:var(--vscode-panel-border,#383838)}.notice.error{color:var(--vscode-errorForeground,#f48771);border-color:var(--vscode-inputValidation-errorBorder,#be1100)}
</style></head><body><div class="app"><header><div class="eyebrow">Qbox Lua / Utilities</div><div class="heading"><h1>Lua utilities</h1><span class="offline">Offline · no code execution</span></div><nav class="tabs" aria-label="Utilities"><button id="tab-hash" role="tab" aria-selected="true" aria-controls="hash-panel">joaat hash</button><button id="tab-color" role="tab" aria-selected="false" aria-controls="color-panel">Colors</button><button id="tab-json" role="tab" aria-selected="false" aria-controls="json-panel">JSON → Lua</button></nav></header><main>
<section class="utility" id="hash-panel" role="tabpanel" aria-labelledby="tab-hash"><h2>Asset name → hash</h2><p class="muted">Cfx ASCII case folding. Input is exact: spaces are retained. Hex, signed and unsigned outputs describe the same 32 bits.</p><label for="hash-input">Model, weapon or other asset name</label><input id="hash-input" maxlength="4096" value="adder" spellcheck="false" placeholder="WEAPON_PISTOL"><p id="hash-error" class="error" role="alert" hidden></p><div id="hash-results"></div></section>
<section class="utility" id="color-panel" role="tabpanel" aria-labelledby="tab-color" hidden><h2>Color picker</h2><p class="muted">RGB and alpha channels use integers from 0 to 255. Lua outputs use these byte values, not normalized 0–1 values.</p><div class="row"><div class="field"><label for="color-picker">Pick RGB</label><input class="color-control" type="color" id="color-picker" value="#0088ff"></div><div class="field"><label for="color-hex">Hex / hex with alpha</label><input id="color-hex" value="#0088FF" maxlength="9" spellcheck="false"></div></div><div class="row">${['red', 'green', 'blue', 'alpha'].map((name) => `<div class="field"><label for="color-${name}">${name[0].toUpperCase() + name.slice(1)}</label><input id="color-${name}" type="number" min="0" max="255" step="1" value="${name === 'red' ? 0 : name === 'green' ? 136 : 255}"></div>`).join('')}</div><p id="color-error" class="error" role="alert" hidden></p><div id="color-results"></div></section>
<section class="utility" id="json-panel" role="tabpanel" aria-labelledby="tab-json" hidden><h2>JSON → Lua table</h2><p class="muted">Object keys keep their order; arrays use explicit indices starting at 1. Numeric tokens are preserved. Generated Lua is editable and never executed.</p><div class="row"><button id="use-selection">Use editor selection</button><div class="field"><label for="null-mode">JSON null</label><select id="null-mode"><option value="json.null">json.null (preserve null values)</option><option value="nil">nil (remove keys / create holes)</option></select></div><button id="convert" class="primary">Convert to Lua</button></div><div class="columns"><div class="field"><label for="json-input">JSON input · up to 128 KiB</label><textarea id="json-input" spellcheck="false" maxlength="131072" placeholder='{"name": "garage", "enabled": true}'></textarea></div><div class="field"><label for="lua-output">Editable Lua preview · up to 512 KiB</label><textarea id="lua-output" spellcheck="false" maxlength="524288" placeholder="Your Lua table appears here"></textarea></div></div><p id="json-error" class="error" role="alert" hidden></p><p id="json-warnings" class="muted" hidden></p><p id="json-note" class="muted">Convert, review, then copy or insert the preview.</p><div class="actions"><button id="copy-lua" disabled>Copy Lua</button><button id="insert-lua" class="primary" disabled>Insert preview</button></div></section>
<div class="target-bar"><div class="row"><strong>Insertion target</strong><button id="capture-target">Use current Lua selection</button></div><p id="target" class="muted">Open a Lua editor to choose an insertion target.</p><p class="muted">Insertion replaces the captured selection. If that file changes, capture it again.</p></div><p id="status" class="notice" role="status" aria-live="polite" hidden></p>
</main></div><script nonce="${safe}" src="${attribute(scriptUri)}"></script></body></html>`;
}
